AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Metrics:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Style/UnlessElse:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
